### PR TITLE
Use Facebook's esprima fork.

### PR DESCRIPTION
**Pull request by eventualbuddha**
I plan to make this same change in all the components of esnext and then bump the version for esnext itself.

### CODE REVIEW

**Comment by fdecampredon** [comment]
@eventualbuddha do you want the ownership or that I add you as a commiter for this repo ? You seems to give more time than myself to this one

**Comment by fdecampredon** [comment]
Also it seems to me that this PR is not complete I guess you need to change `require('esprima')` into `require('esprima-fb')` into the different js files

**Comment by eventualbuddha** [comment]
Whoops! Yeah, I was dealing with a lot of different repos and missed that bit. As for ownership, we can either move to esnext org and keep you as owner or add me as committer to this repo. Your choice.

**Comment by fdecampredon** [comment]
Seems like I need esnext org admin right to transfer it, for the moment I add you as collaborator.

**Pull request merged**
